version: '3.8'

services:
  db:
    build: .
    container_name: questdb
    environment:
      - QDB_DATABASE=qstdb
      - QDB_USER=star
      - QDB_PASSWORD=18star28
    volumes:
      - qstdb_data:/var/lib/questdb/db
    networks:
      - qstdb_network
    ports:
      - "8812:8812"
      - "9000:9000"

  mng:
    build: ./mng
    container_name: questdb-mng
    environment:
      - DATABASE_URL=postgres://star:18star28@db:8812/qstdb
    depends_on:
      - db
    networks:
      - qstdb_network
    ports:
      - "5005:5000"
    volumes:
      - ./mng/data:/app/data # Общий том для доступа к сгенерированным данным

  sender:
    build: ./sender
    container_name: questdb-sender
    environment:
      - DATABASE_URL=postgres://star:18star28@db:8812/qstdb
    depends_on:
      - db
    networks:
      - qstdb_network
    ports:
      - "5006:5000"
    volumes:
      - ./mng/data:/app/data # Общий том для доступа к сгенерированным данным

  receiver:
    build: ./receiver
    container_name: questdb-receiver
    environment:
      - DATABASE_URL=postgres://star:18star28@db:8812/qstdb
    depends_on:
      - db
    networks:
      - qstdb_network
    ports:
      - "5007:5000"
    volumes:
      - ./mng/data:/app/data # Общий том для доступа к сгенерированным данным

networks:
  qstdb_network:
    driver: bridge

volumes:
  qstdb_data:
